### ISSUE TITLE
Proxy Plugin Blueprint Upload Error

### ISSUE THREAD

**Issue by joshuap-cfy** [cloudify-incubator/cloudify-utilities-plugin#44]
What’s the right way to use DeploymentProxy in this new version of 1.2.2?
I have used deployment proxy to implement the following use case:
· Given an existing deployment (deployment_id: network), which exposes several resources through outputs.
· Deploy and install another blueprint, which needs access to the resources created in the deployment above.

I tried to upgrade my proxy node to use the new version of the proxy plugin (1.2.2) following the example in this link: https://github.com/cloudify-incubator/cloudify-utilities-plugin/blob/1.2.2/cloudify_deployment_proxy/examples/test/deployment-proxy.yaml.
My question is: since I’m just importing outputs exposed by an existing deployment, why is it required to provide the “blueprint” input to the proxy node? If I set the blueprint input to empty values, I’m getting an error. The error appears to be resulted from the plugin trying to upload a blueprint. What’s the right way to use DeploymentProxy in this new version of 1.2.2?

**Comment by joshuap-cfy** [comment]
We are currently testing this in v1.2.3 to see if error is resolved.

**Comment by joshuap-cfy** [comment]
After upgrading to version 1.2.3, the following error when trying to deploy a blueprint with a DeploymentProxy node. 1.2.3 does fix the issue of cloudify.nodes.DeploymentProxy (1.2.2) deleted the existing deployment.

Log:
2017-06-22T00:06:55 CFY <proxy> [network_deployment_proxy_ao1g9k.start] Task failed 'cloudify_deployment_proxy.tasks.execute_start' -> 400: Invalid pagination: 1600, max allowed: 1000 [retry 3]
Traceback (most recent call last):
  File "/tmp/pip-build-TeHrVQ/cloudify-plugins-common/cloudify/dispatch.py", line 600, in main
  File "/tmp/pip-build-TeHrVQ/cloudify-plugins-common/cloudify/dispatch.py", line 366, in handle
  File "/opt/mgmtworker/env/plugins/proxy-cfy_util/lib/python2.7/site-packages/cloudify_deployment_proxy/tasks.py", line 36, in execute_start
    return DeploymentProxyBase(_).execute_workflow()
  File "/opt/mgmtworker/env/plugins/proxy-cfy_util/lib/python2.7/site-packages/cloudify_deployment_proxy/__init__.py", line 280, in execute_workflow
    if not self.verify_execution_successful():
  File "/opt/mgmtworker/env/plugins/proxy-cfy_util/lib/python2.7/site-packages/cloudify_deployment_proxy/__init__.py", line 338, in verify_execution_successful
    _log_redirect=self.deployment_logs.get('redirect', True))
  File "/opt/mgmtworker/env/plugins/proxy-cfy_util/lib/python2.7/site-packages/cloudify_deployment_proxy/polling.py", line 202, in poll_workflow_after_execute
    pollster_args=pollster_args)
  File "/opt/mgmtworker/env/plugins/proxy-cfy_util/lib/python2.7/site-packages/cloudify_deployment_proxy/polling.py", line 71, in poll_with_timeout
    if pollster(**pollster_args) != expected_result:
  File "/opt/mgmtworker/env/plugins/proxy-cfy_util/lib/python2.7/site-packages/cloudify_deployment_proxy/polling.py", line 173, in dep_workflow_in_state_pollster
    dep_logs_redirect(_client, _exec.get('id'))
  File "/opt/mgmtworker/env/plugins/proxy-cfy_util/lib/python2.7/site-packages/cloudify_deployment_proxy/polling.py", line 96, in dep_logs_redirect
    last_event + 100, True)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify_rest_client/events.py", line 50, in get
    _sort='@timestamp')
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify_rest_client/events.py", line 99, in list
    params=params)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify_rest_client/client.py", line 194, in get
    stream=stream)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify_rest_client/client.py", line 179, in do_request
    verify=self.get_request_verify())
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify_rest_client/client.py", line 129, in _do_request
    self._raise_client_error(response, request_url)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify_rest_client/client.py", line 92, in _raise_client_error
    server_traceback=server_traceback)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify_rest_client/client.py", line 103, in _prepare_and_raise_exception
    status_code, error_code=error_code)
CloudifyClientError: 400: Invalid pagination: 1600, max allowed: 1000

**Comment by 0lvin** [comment]
Should be fixed in 149aca363d1e101caaf44edb2b28274b0295d85b

**Comment by EarthmanT** [comment]
fixed in 1.2.5
