### ISSUE TITLE
DeploymentProxy - Tasks failed to create existing resources

### ISSUE THREAD

**Issue by joshuap-cfy** [cloudify-incubator/cloudify-utilities-plugin#49]
The “pagination” issue is fixed in 1.2.4 but getting another error while trying to use existing resources with DeploymentProxy.
 
Summary:
Tasks failed to create existing resources
 
Symptom:
The DeploymentProxy node itself is created successfully and the resource_id(s) exposed through the output of the parent deployment are successfully brought in. However, the task to create an existing resource failed.
 
Logs (full log is attached):
2017-06-27T20:50:46 LOG <proxy> [network_deployment_proxy_wdby5c.start] DEBUG: Polling succeeded!
2017-06-27T20:50:46 LOG <proxy> [network_deployment_proxy_wdby5c.start] DEBUG: 
Traceback (most recent call last):
  File "/tmp/pip-build-TeHrVQ/cloudify-plugins-common/cloudify/dispatch.py", line 600, in main
  File "/tmp/pip-build-TeHrVQ/cloudify-plugins-common/cloudify/dispatch.py", line 366, in handle
  File "/opt/mgmtworker/env/plugins/cloudify-aws-plugin-1.4.11/lib/python2.7/site-packages/cloudify_aws/vpc/subnet.py", line 31, in create_subnet
    return Subnet().create_helper(args)
  File "/opt/mgmtworker/env/plugins/cloudify-aws-plugin

**Comment by EarthmanT** [comment]
fixed in 1.2.5
