### ISSUE TITLE
deployment_proxy (v. 1.5.1) - attribute error on deployment creation

### ISSUE THREAD

**Issue by astianseb** [cloudify-incubator/cloudify-utilities-plugin#93]
When creating deployment with deployment_proxy:
`  branch_fw:
    type: cloudify.nodes.DeploymentProxy
    properties:
      resource_config:
        blueprint:
          id: { get_input: branch_fw_blueprint_name }
          external_resource: true
        deployment:
          id: { get_input: branch_fw_deployment_name }
          external_resource: false
          inputs:
    relationships:
      - type: cloudify.relationships.depends_on
        target: branch_rtr
`
Install workflow is failing with following error:
`
2018-03-28 11:31:13.733  CFY <vb-test> [branch_rtr_0o0w4p.start] Task failed 'cloudify_deployment_proxy.tasks.execute_start' -> 'NoneType' object has no attribute 'items' [retry 2/60]
Traceback (most recent call last):
  File "/tmp/pip-build-TIPQg9/cloudify-plugins-common/cloudify/dispatch.py", line 635, in main
  File "/tmp/pip-build-TIPQg9/cloudify-plugins-common/cloudify/dispatch.py", line 391, in handle
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-utilities-plugin-1.5.1/lib/python2.7/site-packages/cloudify_deployment_proxy/tasks.py", line 36, in execute_start
    return DeploymentProxyBase(_).execute_workflow()
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-utilities-plugin-1.5.1/lib/python2.7/site-packages/cloudify_deployment_proxy/__init__.py", line 289, in execute_workflow
    return self.post_execute_deployment_proxy()
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-utilities-plugin-1.5.1/lib/python2.7/site-packages/cloudify_deployment_proxy/__init__.py", line 337, in post_execute_deployment_proxy
    for key, val in self.deployment_outputs.items():
AttributeError: 'NoneType' object has no attribute 'items'
`

**Comment by EarthmanT** [comment]
Fixed in #95
